version: "3.9"
services:
  downloader:
    build:
      context: .
    image: aws-cli-cron:latest
    container_name: aws-cli-cron
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      - credentials:/root/.aws
      - cron:/cron

volumes:
  credentials:
    name: aws_credentials
    driver: local
  cron:
    name: aws_cron
    driver: local